
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Student
 */
public class eligibility extends javax.swing.JFrame {

    /**
     * Creates new form eligibility
     */
    public eligibility() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        t1 = new javax.swing.JTextField();
        c1 = new javax.swing.JComboBox<>();
        c2 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Algerian", 3, 48)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("WELCOME TO PST");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, 470, 33));

        jLabel2.setFont(new java.awt.Font("Book Antiqua", 3, 16)); // NOI18N
        jLabel2.setText("AGE");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 195, 25));

        jLabel3.setFont(new java.awt.Font("Book Antiqua", 3, 16)); // NOI18N
        jLabel3.setText("CATEGORY");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 195, 25));

        jLabel4.setFont(new java.awt.Font("Book Antiqua", 3, 16)); // NOI18N
        jLabel4.setText("PASSING YEAR OF 12TH CLASS OR EQUIVALENT");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 390, 20));

        t1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                t1KeyTyped(evt);
            }
        });
        getContentPane().add(t1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 160, 172, -1));

        c1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "GENERAL", "OBC", "OBC-NCL(INCLUDING PWD)", "SC(INCLUDING PWD)", "ST(INCLUDING PWD)", "GENERAL-PWD", "OBC-PWD" }));
        getContentPane().add(c1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 220, 172, -1));

        c2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2017", "2016", "2015", "2014(or earlier)" }));
        getContentPane().add(c2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 280, 172, -1));

        jButton1.setFont(new java.awt.Font("Book Antiqua", 3, 14)); // NOI18N
        jButton1.setText("CHECK ELIGIBILTY");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 370, 170, -1));

        jButton2.setFont(new java.awt.Font("Book Antiqua", 3, 14)); // NOI18N
        jButton2.setText("BACK");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(419, 470, 80, -1));

        jButton3.setFont(new java.awt.Font("Book Antiqua", 3, 14)); // NOI18N
        jButton3.setText("EXIT");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 470, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BL10_Choosing_righ_2335947f.jpg"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(-4, 0, 630, 520));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void t1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t1KeyTyped
        char key = evt.getKeyChar();
        if ((key>='0' && key<='9'))
        {}else{
            evt.consume();}         // TODO add your handling code here:
    }//GEN-LAST:event_t1KeyTyped

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int a=-1,b=-1,c=-1;
        if(t1.getText().isEmpty())
        {a=-1;b=-1;c=-1;}
        else{a= Integer.parseInt(t1.getText());
            b=c1.getSelectedIndex();
            c=c2.getSelectedIndex();
        }
        if(a==-1||b==-1||c==-1)
        {JOptionPane.showMessageDialog(this,"PLEASE ENTER COMPLETE INFORMATION");}
        else   if(c!=3)
        {
            if(a>=17&&a<=22)
            {
                JOptionPane.showMessageDialog(this,"YOU ARE ELIGIBLE");

            }
            else if(a>=22&&a<=25&&b>=2&&b<=6)
            {
                JOptionPane.showMessageDialog(this,"YOU ARE ELIGIBLE");
            }
            else
            {JOptionPane.showMessageDialog(this,"YOU ARE NOT ELIGIBLE !! ");}
        }
        else{JOptionPane.showMessageDialog(this,"YOU ARE NOT ELIGIBLE !! ");}
        // TODO add your handling code here:}
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        int x=JOptionPane.showConfirmDialog(this,"Do you want to exit?","Confirm",JOptionPane.YES_NO_OPTION);
        if(x==0)
        {
            System.exit(0);         // TODO add your handling code here:
        }             // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
 new home_page().setVisible(true);this.dispose();          // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(eligibility.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(eligibility.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(eligibility.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(eligibility.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new eligibility().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> c1;
    private javax.swing.JComboBox<String> c2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField t1;
    // End of variables declaration//GEN-END:variables
}
