
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Student
 */
public class faq extends javax.swing.JFrame {

    /**
     * Creates new form faq
     */
    public faq() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        c1 = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        ta = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Book Antiqua", 3, 36)); // NOI18N
        jLabel1.setText("FAQ ->");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 170, 150, 46));

        c1.setFont(new java.awt.Font("Segoe Print", 3, 18)); // NOI18N
        c1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Are there any books that I can study to prepare for PST?", " I passed my XII standard in 2014 (or earlier). Can you make an exemption for me?", "How is that students from all academic streams are eligible to apply for PST?", " Why is PST not held in my city? Can you have a center in my city?", " I appeared for PST 2017 but did not qualify. Can I appear for PST 2018?", " What will be the format of the PST question paper?", " Will there be negative marking?", " I made a mistake while filling up the application form. What should I do?", " I am an OBC candidate. Can I apply under the OBC category?", " What are the validity requirements for the OBC-NCL certificate?", "I do not have a birth certificate for proof of date of birth. What should I do?", " " }));
        c1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                c1ItemStateChanged(evt);
            }
        });
        c1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c1ActionPerformed(evt);
            }
        });
        getContentPane().add(c1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 170, 850, 46));

        ta.setEditable(false);
        ta.setColumns(20);
        ta.setLineWrap(true);
        ta.setRows(5);
        ta.setWrapStyleWord(true);
        ta.setFocusable(false);
        jScrollPane1.setViewportView(ta);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 270, 577, 154));

        jButton1.setFont(new java.awt.Font("Forte", 3, 36)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 102, 102));
        jButton1.setText("ANSWERS");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 270, 230, 50));

        jLabel4.setFont(new java.awt.Font("Matura MT Script Capitals", 3, 48)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 0, 0));
        jLabel4.setText("Frequently Asked Questions(FAQ)");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 10, 1000, 60));

        jButton2.setFont(new java.awt.Font("Georgia", 3, 24)); // NOI18N
        jButton2.setText("Back To Homepage");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 860, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/reading-book.jpg"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1790, 920));

        jLabel7.setFont(new java.awt.Font("Book Antiqua", 3, 18)); // NOI18N
        jLabel7.setText("Your EMAIL-ID   ->");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 310, 180, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void c1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int a= c1.getSelectedIndex();
        if(a==0)
        {ta.setText("PST is a design aptitude test. Aptitude tests assume that individuals have inherent strengths and weaknesses, and are naturally inclined toward success or failure in certain areas based on their inherent characteristics. Except for the syllabi section 'Environmental and social awareness' which will test your general awareness in the topics outlined under it, the remaining five sections will test your aptitude. Consequently there are no text or reference books that we can recommend.");}
        else if(a==1)
        {ta.setText("No");}
        else if(a==2)
        {ta.setText("Design is an interdisciplinary activity. Holistic design considers the sciences, arts, technology, economics, media, policy, society and culture. Successful designers have backgrounds in the arts, sciences and the humanities. However do note that candidates from the Science Stream with Physics, Chemistry and Maths as subjects are eligible to apply to B.Des atall the three institutes while candidates from any other stream (Science without Maths or Physics or Chemistry, Commerce, and Arts & Humanities) are eligible to apply to only IIT Bombay and IIITDM Jabalpur.");}
        else if(a==3)
        {ta.setText("Conducting a national level exam is a massive exercise. The PST 2018 Committee carefully considered all logistical and operational factors, including information based on PST 2016 & 2017 applicants, before deciding on the 19 cities where PST 2018 will be held. In addition to the 14 cities where PS 2018 was held, 5 new cities have been added for PST 2018.");}
        else if(a==4)
        {ta.setText("Yes you can, provided you meet the age and year of passing qualification certificate criteria as mentioned here. However do note that a candidate can attempt PST for a maximum of two times only and that too in consecutive years, and that the PST score is valid only for admissions in the corresponding academic year.");}
        else if (a==5)
        {ta.setText("For detailed information about the question paper visit our site");}
        else if(a==6)
        {ta.setText("Only Section C of the question paper has negative marking. ");}
        else if(a==7)
        {ta.setText("Send an email to pst@iitb.ac.in with details related to your application (registration number, candidate name, and mobile phone number) and describing clearly the nature of the mistake. Where possible we will rectify the mistake, or advise you on what to do next. However do note that it will entirely be the responsibility of the candidate to provide the correct information regarding the category, the qualifying examination (XII Class or equivalent), and the date of birth in the application form.");}
        else if(a==8)
        {ta.setText("There is NO reservation under the OBC category. ONLY OBC candidates with the NCL (Non-Creamy Layer) certificate can apply under the OBC-NCL category. OBC candidates WITHOUT the NCL certificate must apply under the OPEN category.");}
        else if(a==9)
        {ta.setText("The OBC-NCL certificate must be issued on or after April 1, 2016 and conforming to the latest guidelines of the Government of India. However PST qualified candidates when they apply for for B.Des admissions in June 2018, must submit an updated OBC-NCL certificate that is issued on or after April 1, 2017 and conforming to the latest guidelines of the Government of India. Visit www.ncbc.nic.in for the latest guidelines and updates of the Central List of State-wise OBCs.");}
        else if(a==10)
        {ta.setText("If you do not have a birth certificate you can upload copy of passport, or copy of Aadhaar Card or copy of X class marksheet/school leaving certificate showing your DOB.");}
        else if(a==11)
        {

        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void c1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_c1ItemStateChanged
       // TODO add your handling code here:
    }//GEN-LAST:event_c1ItemStateChanged

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        new home_page().setVisible(true);this.dispose();           // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(faq.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(faq.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(faq.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(faq.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new faq().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> c1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea ta;
    // End of variables declaration//GEN-END:variables
}
