
import java.util.*;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Student
 */
public class instructions_1 extends javax.swing.JFrame {

    /**
     * Creates new form instructions_1
     */
    public instructions_1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        t2 = new javax.swing.JTextArea();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        t1 = new javax.swing.JTextField();
        p1 = new javax.swing.JProgressBar();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        t2.setEditable(false);
        t2.setBackground(new java.awt.Color(255, 153, 102));
        t2.setColumns(20);
        t2.setFont(new java.awt.Font("Georgia", 0, 16)); // NOI18N
        t2.setForeground(new java.awt.Color(0, 102, 102));
        t2.setRows(5);
        t2.setText("                                                                      Paper Specific Instructions\n1.The examination is of 1 hours duration. There are a total of 17 questions carrying a total of 51 marks. \n2.The entire paper is divided into FOUR sections A, B, C and D. All sections are compulsory.\n3.Questions in each section are of different types.\n4.Section A (15 Marks) contains a total of 5 Multiple Choice Questions (MCQ).  \nEach McQ type question  have one correct choice that are correct out of the four given choices.\n\nQuestions not attempted will result in zero marks. \nQuestions 1-5 belong to this section.\nThis checks the IQ of candidate.\nSection B (15 Marks) contains a total of 5 Multiple Choice Questions (MCQ). \nThe candidate gets 3 marks only if ALL the correct answers and no wrong answers are selected.\nThere is NO NEGATIVE or PARTIAL marking for this section. Questions not attempted will be given zero marks. \nQuestions 21-50 belong to this section. \nThere are 10 questions each of physics, chemistry, maths in this section.\nSection C (150 Marks) contains a total of 50 Multiple Choice Questions (MCQ). \nEach MCQ has four choices out of which only one is the correct answer.\nThere is NEGATIVE marking for this section. \nEach correct answer will be awarded 3 marks and each wrong answer will receive −1 (minus 1) marks. \nQuestions not attempted will be given zero marks. \nQuestions 51-100 belong to this section.\nCalculators, charts, graph sheets, tables, cellular phone or other electronic gadgets are NOT allowed\nin the examination hall.\nA Scribble Pad will be provided for rough work.\nNOTE: The above instructions are of PST 2015,\nThe instructions for PST 2018 will be different and must be read at the time of PST 2018 exam.\nThis Mock Question Paper contains only 10 questions for each section which should be taken only as \na sample.");
        t2.setOpaque(false);
        jScrollPane2.setViewportView(t2);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 62, 910, 472));

        jButton3.setFont(new java.awt.Font("Algerian", 3, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 51, 51));
        jButton3.setText("CONTINUE");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 550, 170, -1));

        jButton4.setFont(new java.awt.Font("Algerian", 3, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 0, 0));
        jButton4.setText("EXIT");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 560, -1, -1));

        t1.setFont(new java.awt.Font("Book Antiqua", 3, 12)); // NOI18N
        t1.setText("0%");
        t1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t1ActionPerformed(evt);
            }
        });
        getContentPane().add(t1, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 540, 40, 30));
        getContentPane().add(p1, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 540, 162, 30));

        jLabel1.setFont(new java.awt.Font("Algerian", 3, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("INSTRUCTIONS");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 0, -1, 60));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/exams.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 930, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        final Timer t=new Timer();
           
        
        
                
                
        t.scheduleAtFixedRate(new TimerTask(){

            public void run(){
                p1.setValue(p1.getValue()+5);
                t1.setText(""+p1.getValue()+"%");
                if(p1.getValue()==100)
                {
                    t.cancel();
                    func();

                }
            }

        }, 0, 100);      // add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed
public void func(){new instructions_2().setVisible(true);this.dispose();}
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        int x=JOptionPane.showConfirmDialog(this,"Do you want to exit","Confirm",JOptionPane.YES_NO_OPTION);
        if(x==0)
        {
            System.exit(0);}
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void t1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(instructions_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(instructions_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(instructions_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(instructions_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new instructions_1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JProgressBar p1;
    private javax.swing.JTextField t1;
    private javax.swing.JTextArea t2;
    // End of variables declaration//GEN-END:variables
}
