
import com.mysql.jdbc.Connection;
import com.mysql.jdbc.Statement;
import java.sql.DriverManager;
import java.sql.ResultSet;
import javax.swing.*;
import java.util.*;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Prakhar
 */
public class login_mainexam extends javax.swing.JFrame {

    /**
     * Creates new form login_mainexam
     */
    public login_mainexam() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        t1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        t2 = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        t3 = new javax.swing.JTextField();
        p1 = new javax.swing.JProgressBar();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Algerian", 3, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 153, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("WELCOME TO PST");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, 340, 40));
        getContentPane().add(t1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 70, 300, 30));

        jLabel2.setFont(new java.awt.Font("Book Antiqua", 3, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 102, 0));
        jLabel2.setText("E-MAIL ADDRESS");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, 180, 34));
        getContentPane().add(t2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 130, 300, 30));

        jLabel3.setFont(new java.awt.Font("Book Antiqua", 3, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 102, 102));
        jLabel3.setText("PASSWORD");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, 150, 34));

        t3.setEditable(false);
        t3.setFont(new java.awt.Font("Book Antiqua", 3, 12)); // NOI18N
        t3.setText("0%");
        getContentPane().add(t3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 280, 40, 30));
        getContentPane().add(p1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 280, 161, 30));

        jButton1.setFont(new java.awt.Font("Georgia", 3, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 102, 0));
        jButton1.setText("START THE TEST");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 230, -1, 30));

        jButton2.setFont(new java.awt.Font("Georgia", 3, 12)); // NOI18N
        jButton2.setText("Back To Homepage");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lmc_login.jpg"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 670, 350));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    int a=0;
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String emailid="";String password="";
        try
        {
          Class.forName("java.sql.DriverManager");
          Connection con=(Connection)
                  DriverManager.getConnection("jdbc:mysql://localhost:3306/pst","root","iamarapperA");
          Statement stmt=(Statement)con.createStatement();
          String query="SELECT emailid, password FROM signup;";
          ResultSet rs=stmt.executeQuery(query);
            while (rs.next())
                    {
                   
                    
                     emailid=rs.getString("emailid");
                     password=rs.getString("password");
                    
                        if(t1.getText().equalsIgnoreCase(emailid)&&t2.getText().equals(password))
        {
            int x=JOptionPane.showConfirmDialog(this,"Do you want to Continue?","Confirm",JOptionPane.YES_NO_OPTION);
                  //  int x=JOptionPane.showConfirmDialog(this,"Do you want to exit","Confirm",JOptionPane.YES_NO_OPTION);

            if(x==0)
            {final java.util.Timer t=new java.util.Timer();
                t.scheduleAtFixedRate(new TimerTask(){

                    public void run(){
                        p1.setValue(p1.getValue()+2);
                   t3.setText(""+p1.getValue());
                        if(p1.getValue()==100)
                        {
                            t.cancel();
                            ++a;
                           func(); 
                           

                        }
                    }

                }, 0, 10);}
            } // else{a++;}
                    }  
            if(a!=0){JOptionPane.showMessageDialog(this,"PASSWORD E-MAIL DOESN'T MATCH");}
            //else{JOptionPane.showMessageDialog(this,"PASSWORD E-MAIL DOESN'T MATCH");}
        }
        catch(Exception e)
                {
                    JOptionPane.showMessageDialog(rootPane,e.getMessage());
                }
               // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed
public void func(){   new instruction_3().setVisible(true);this.dispose();}
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        new home_page().setVisible(true);this.dispose();           // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login_mainexam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login_mainexam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login_mainexam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login_mainexam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login_mainexam().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JProgressBar p1;
    private javax.swing.JTextField t1;
    private javax.swing.JPasswordField t2;
    private javax.swing.JTextField t3;
    // End of variables declaration//GEN-END:variables
}
