/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Student
 */
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.DriverManager;import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

public class mock_test extends javax.swing.JFrame {

    
  static Connection con;
static Statement stmt;
public void abc()
        {
        try{
        Class.forName("java.sql.DriverManager");
        con=(Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/questions","root","iamarapperA");
        stmt=(Statement)con.createStatement();       
        }
        catch(ClassNotFoundException | SQLException f)
    
            {
                JOptionPane.showMessageDialog(this, f.getMessage());
            }

  
        
        
        }
    
    public mock_test() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        tb = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        b1 = new javax.swing.JButton();
        b3 = new javax.swing.JButton();
        b4 = new javax.swing.JButton();
        b5 = new javax.swing.JButton();
        b2 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        t1 = new javax.swing.JTextArea();
        r1 = new javax.swing.JRadioButton();
        r2 = new javax.swing.JRadioButton();
        r3 = new javax.swing.JRadioButton();
        r4 = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        b6 = new javax.swing.JButton();
        b8 = new javax.swing.JButton();
        b9 = new javax.swing.JButton();
        b10 = new javax.swing.JButton();
        b7 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        t2 = new javax.swing.JTextArea();
        r5 = new javax.swing.JRadioButton();
        r6 = new javax.swing.JRadioButton();
        r7 = new javax.swing.JRadioButton();
        r8 = new javax.swing.JRadioButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        b12 = new javax.swing.JButton();
        b13 = new javax.swing.JButton();
        b14 = new javax.swing.JButton();
        b15 = new javax.swing.JButton();
        b16 = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        t3 = new javax.swing.JTextArea();
        r9 = new javax.swing.JRadioButton();
        r10 = new javax.swing.JRadioButton();
        r11 = new javax.swing.JRadioButton();
        r12 = new javax.swing.JRadioButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        b17 = new javax.swing.JButton();
        b21 = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        t4 = new javax.swing.JTextArea();
        r13 = new javax.swing.JRadioButton();
        r14 = new javax.swing.JRadioButton();
        r15 = new javax.swing.JRadioButton();
        r16 = new javax.swing.JRadioButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Algerian", 3, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText(" PLEASE ANSWER PATIENTLY!!   ALL THE BEST!!!");

        tb.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tb.setFont(new java.awt.Font("Book Antiqua", 3, 14)); // NOI18N
        tb.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                tbStateChanged(evt);
            }
        });
        tb.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tbFocusGained(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPanel2FocusGained(evt);
            }
        });

        b1.setBackground(new java.awt.Color(255, 255, 255));
        b1.setFont(new java.awt.Font("Meiryo", 1, 12)); // NOI18N
        b1.setText("1");
        b1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1ActionPerformed(evt);
            }
        });

        b3.setBackground(new java.awt.Color(255, 255, 255));
        b3.setFont(new java.awt.Font("Meiryo", 1, 12)); // NOI18N
        b3.setText("3");
        b3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b3ActionPerformed(evt);
            }
        });

        b4.setBackground(new java.awt.Color(255, 255, 255));
        b4.setFont(new java.awt.Font("Meiryo", 1, 12)); // NOI18N
        b4.setText("4");
        b4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b4ActionPerformed(evt);
            }
        });

        b5.setBackground(new java.awt.Color(255, 255, 255));
        b5.setFont(new java.awt.Font("Meiryo", 1, 12)); // NOI18N
        b5.setText("5");
        b5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b5ActionPerformed(evt);
            }
        });

        b2.setBackground(new java.awt.Color(255, 255, 255));
        b2.setFont(new java.awt.Font("Meiryo", 1, 12)); // NOI18N
        b2.setText("2");
        b2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(b1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                        .addComponent(b2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23)
                        .addComponent(b3)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(b4, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(b5, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(72, 72, 72))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b3, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b4, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b5, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        t1.setEditable(false);
        t1.setColumns(20);
        t1.setFont(new java.awt.Font("Georgia", 3, 14)); // NOI18N
        t1.setLineWrap(true);
        t1.setRows(5);
        t1.setWrapStyleWord(true);
        t1.setFocusable(false);
        jScrollPane2.setViewportView(t1);

        buttonGroup1.add(r1);
        r1.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        r1.setText("A.");
        r1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(r2);
        r2.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        r2.setText("B.");

        buttonGroup1.add(r3);
        r3.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        r3.setText("C.");
        r3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r3ActionPerformed(evt);
            }
        });

        buttonGroup1.add(r4);
        r4.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        r4.setText("D.");

        jButton1.setText("SAVE AND NEXT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("SUBMIT");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Clear");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(r1, javax.swing.GroupLayout.DEFAULT_SIZE, 284, Short.MAX_VALUE)
                            .addComponent(r3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(r2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(r4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(14, 14, 14))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(57, 57, 57)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 143, Short.MAX_VALUE)
                        .addComponent(jButton2)
                        .addGap(45, 45, 45)))
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(19, 19, 19)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 536, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(276, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 178, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(r1)
                            .addComponent(r2))
                        .addGap(33, 33, 33)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(r3)
                            .addComponent(r4))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(jButton2)
                            .addComponent(jButton3))
                        .addGap(45, 45, 45))))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(222, Short.MAX_VALUE)))
        );

        tb.addTab("SECTION A", jPanel2);

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel7.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPanel7FocusGained(evt);
            }
        });

        b6.setBackground(new java.awt.Color(255, 255, 255));
        b6.setFont(new java.awt.Font("Meiryo", 1, 12)); // NOI18N
        b6.setText("6");
        b6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b6ActionPerformed(evt);
            }
        });

        b8.setBackground(new java.awt.Color(255, 255, 255));
        b8.setFont(new java.awt.Font("Meiryo", 1, 12)); // NOI18N
        b8.setText("8");
        b8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b8ActionPerformed(evt);
            }
        });

        b9.setBackground(new java.awt.Color(255, 255, 255));
        b9.setFont(new java.awt.Font("Meiryo", 1, 12)); // NOI18N
        b9.setText("9");
        b9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b9ActionPerformed(evt);
            }
        });

        b10.setBackground(new java.awt.Color(255, 255, 255));
        b10.setFont(new java.awt.Font("Meiryo", 1, 12)); // NOI18N
        b10.setText("10");
        b10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b10ActionPerformed(evt);
            }
        });

        b7.setBackground(new java.awt.Color(255, 255, 255));
        b7.setFont(new java.awt.Font("Meiryo", 1, 12)); // NOI18N
        b7.setText("7");
        b7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(b6, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                        .addComponent(b7, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(b8, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(b9, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(b10)
                        .addGap(57, 57, 57)))
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b6, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b7, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b8, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b9, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b10, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        t2.setEditable(false);
        t2.setColumns(20);
        t2.setFont(new java.awt.Font("Georgia", 3, 14)); // NOI18N
        t2.setLineWrap(true);
        t2.setRows(5);
        t2.setWrapStyleWord(true);
        t2.setFocusable(false);
        jScrollPane3.setViewportView(t2);

        buttonGroup1.add(r5);
        r5.setFont(new java.awt.Font("Georgia", 0, 8)); // NOI18N
        r5.setText("A.");
        r5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r5ActionPerformed(evt);
            }
        });

        buttonGroup1.add(r6);
        r6.setFont(new java.awt.Font("Georgia", 0, 8)); // NOI18N
        r6.setText("B.");

        buttonGroup1.add(r7);
        r7.setFont(new java.awt.Font("Georgia", 0, 8)); // NOI18N
        r7.setText("C.");
        r7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r7ActionPerformed(evt);
            }
        });

        buttonGroup1.add(r8);
        r8.setFont(new java.awt.Font("Georgia", 0, 8)); // NOI18N
        r8.setText("D.");

        jButton4.setText("SAVE AND NEXT");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("SUBMIT");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("Clear");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(r5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(r7, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 15, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(r8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(11, 11, 11))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(r6, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(5, 5, 5)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(57, 57, 57)
                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton5)
                        .addGap(45, 45, 45)))
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel7Layout.createSequentialGroup()
                    .addGap(19, 19, 19)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 536, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(263, Short.MAX_VALUE)))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                        .addGap(0, 188, Short.MAX_VALUE)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(r5)
                            .addComponent(r6))
                        .addGap(33, 33, 33)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(r7)
                            .addComponent(r8))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton4)
                            .addComponent(jButton5)
                            .addComponent(jButton6))
                        .addGap(45, 45, 45))))
            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel7Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(220, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        tb.addTab("SECTION B", jPanel3);

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jPanel9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel9.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPanel9FocusGained(evt);
            }
        });

        b12.setBackground(new java.awt.Color(255, 255, 255));
        b12.setFont(new java.awt.Font("Meiryo", 1, 12)); // NOI18N
        b12.setText("11");
        b12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b12ActionPerformed(evt);
            }
        });

        b13.setBackground(new java.awt.Color(255, 255, 255));
        b13.setFont(new java.awt.Font("Meiryo", 1, 12)); // NOI18N
        b13.setText("13");
        b13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b13ActionPerformed(evt);
            }
        });

        b14.setBackground(new java.awt.Color(255, 255, 255));
        b14.setFont(new java.awt.Font("Meiryo", 1, 12)); // NOI18N
        b14.setText("14");
        b14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b14ActionPerformed(evt);
            }
        });

        b15.setBackground(new java.awt.Color(255, 255, 255));
        b15.setFont(new java.awt.Font("Meiryo", 1, 12)); // NOI18N
        b15.setText("15");
        b15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b15ActionPerformed(evt);
            }
        });

        b16.setBackground(new java.awt.Color(255, 255, 255));
        b16.setFont(new java.awt.Font("Meiryo", 1, 12)); // NOI18N
        b16.setText("12");
        b16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b16ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(b14)
                        .addGap(18, 18, 18)
                        .addComponent(b15, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(b12)
                        .addGap(18, 18, 18)
                        .addComponent(b16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(b13)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b12, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b16, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b13, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b15, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b14, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        t3.setEditable(false);
        t3.setColumns(20);
        t3.setFont(new java.awt.Font("Georgia", 3, 14)); // NOI18N
        t3.setLineWrap(true);
        t3.setRows(5);
        t3.setWrapStyleWord(true);
        t3.setFocusable(false);
        jScrollPane4.setViewportView(t3);

        buttonGroup1.add(r9);
        r9.setText("A.");
        r9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r9ActionPerformed(evt);
            }
        });

        buttonGroup1.add(r10);
        r10.setText("B.");

        buttonGroup1.add(r11);
        r11.setText("C.");
        r11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r11ActionPerformed(evt);
            }
        });

        buttonGroup1.add(r12);
        r12.setText("D.");

        jButton7.setText("SAVE AND NEXT");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setText("SUBMIT");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton9.setText("Clear");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(r9, javax.swing.GroupLayout.DEFAULT_SIZE, 285, Short.MAX_VALUE)
                            .addComponent(r11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(r10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(r12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(57, 57, 57)
                        .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 137, Short.MAX_VALUE)
                        .addComponent(jButton8)
                        .addGap(37, 37, 37)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
            .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel9Layout.createSequentialGroup()
                    .addGap(19, 19, 19)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 536, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(263, Short.MAX_VALUE)))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap(195, Short.MAX_VALUE)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(r9)
                    .addComponent(r10))
                .addGap(33, 33, 33)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(r11)
                    .addComponent(r12, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton7)
                    .addComponent(jButton8)
                    .addComponent(jButton9))
                .addGap(45, 45, 45))
            .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel9Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(220, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        tb.addTab("SECTION C", jPanel4);

        jPanel11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel11.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPanel11FocusGained(evt);
            }
        });

        b17.setBackground(new java.awt.Color(255, 255, 255));
        b17.setFont(new java.awt.Font("Meiryo", 1, 12)); // NOI18N
        b17.setText("16");
        b17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b17ActionPerformed(evt);
            }
        });

        b21.setBackground(new java.awt.Color(255, 255, 255));
        b21.setFont(new java.awt.Font("Meiryo", 1, 12)); // NOI18N
        b21.setText("17");
        b21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b21ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(b17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addComponent(b21)
                .addGap(67, 67, 67))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b17, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b21, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        t4.setEditable(false);
        t4.setColumns(20);
        t4.setFont(new java.awt.Font("Georgia", 3, 14)); // NOI18N
        t4.setLineWrap(true);
        t4.setRows(5);
        t4.setWrapStyleWord(true);
        t4.setFocusable(false);
        jScrollPane5.setViewportView(t4);

        buttonGroup1.add(r13);
        r13.setFont(new java.awt.Font("Georgia", 0, 8)); // NOI18N
        r13.setText("A.");
        r13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r13ActionPerformed(evt);
            }
        });

        buttonGroup1.add(r14);
        r14.setFont(new java.awt.Font("Georgia", 0, 8)); // NOI18N
        r14.setText("B.");
        r14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r14ActionPerformed(evt);
            }
        });

        buttonGroup1.add(r15);
        r15.setFont(new java.awt.Font("Georgia", 0, 8)); // NOI18N
        r15.setText("C.");
        r15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r15ActionPerformed(evt);
            }
        });

        buttonGroup1.add(r16);
        r16.setFont(new java.awt.Font("Georgia", 0, 8)); // NOI18N
        r16.setText("D.");

        jButton10.setText("SAVE AND NEXT");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jButton11.setText("SUBMIT");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        jButton12.setText("Clear");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(r13, javax.swing.GroupLayout.DEFAULT_SIZE, 288, Short.MAX_VALUE)
                            .addComponent(r15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(r14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(r16, javax.swing.GroupLayout.DEFAULT_SIZE, 243, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(76, 76, 76)
                        .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 126, Short.MAX_VALUE)
                        .addComponent(jButton11)
                        .addGap(45, 45, 45)))
                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel11Layout.createSequentialGroup()
                    .addGap(19, 19, 19)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 536, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(265, Short.MAX_VALUE)))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                        .addGap(0, 184, Short.MAX_VALUE)
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                                .addComponent(r13)
                                .addGap(33, 33, 33)
                                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(r15)
                                    .addComponent(r16))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jButton10)
                                    .addComponent(jButton11)
                                    .addComponent(jButton12))
                                .addGap(45, 45, 45))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                                .addComponent(r14)
                                .addGap(146, 146, 146))))))
            .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel11Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(222, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        tb.addTab("SECTION D", jPanel5);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 840, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(68, 68, 68)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 670, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(tb, javax.swing.GroupLayout.PREFERRED_SIZE, 840, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 448, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(11, 11, 11)
                    .addComponent(tb, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
static int a[]=new int[17];static int i=0;
static String q[]=new String[17];
static String a1[]=new String[17];
static String b11[]=new String[17];
static String c1[]=new String[17];
static String d1[]=new String[17];
//    private void formWindowOpened(java.awt.event.WindowEvent evt) {                                  
//
//    }  
    private void b1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1ActionPerformed
        i=0;        // TODO add your handling code here:
        if(a[0]==1) {r1.setSelected(true);}
        else if(a[0]==2){r2.setSelected(true);}
        else if(a[0]==3){r3.setSelected(true);}
        else if(a[0]==4){r4.setSelected(true);}
        else{buttonGroup1.clearSelection();}
        t1.setText(q[0]);
        r1.setText(a1[0]);
        r2.setText(b11[0]);
        r3.setText(c1[0]);
        r4.setText(d1[0]);
        if(a[i]==0){b1.setBackground(Color.red);}
        else{b1.setBackground(Color.cyan);}
    }//GEN-LAST:event_b1ActionPerformed

    private void b3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b3ActionPerformed
        i=2;if(a[2]==1) {r1.setSelected(true);}
        else if(a[2]==2){r2.setSelected(true);}
        else if(a[2]==3){r3.setSelected(true);}
        else if(a[2]==4){r4.setSelected(true);}
        else{buttonGroup1.clearSelection();}
        t1.setText(q[2]);
        r1.setText(a1[2]);
        r2.setText(b11[2]);
        r3.setText(c1[2]);
        r4.setText(d1[2]);
        if(a[i]==0){b3.setBackground(Color.red);}
        else{b3.setBackground(Color.cyan);}// TODO add your handling code here:
    }//GEN-LAST:event_b3ActionPerformed

    private void b4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b4ActionPerformed
        i=3;if(a[3]==1) {r1.setSelected(true);}
        else if(a[3]==2){r2.setSelected(true);}
        else if(a[3]==3){r3.setSelected(true);}
        else if(a[3]==4){r4.setSelected(true);}
        else{buttonGroup1.clearSelection();}
        t1.setText(q[3]);
        r1.setText(a1[3]);
        r2.setText(b11[3]);
        r3.setText(c1[3]);
        r4.setText(d1[3]);
        if(a[i]==0){b4.setBackground(Color.red);}
        else{b4.setBackground(Color.cyan);}// TODO add your handling code here:
    }//GEN-LAST:event_b4ActionPerformed

    private void b5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b5ActionPerformed
        i=4;if(a[4]==1) {r1.setSelected(true);}
        else if(a[4]==2){r2.setSelected(true);}
        else if(a[4]==3){r3.setSelected(true);}
        else if(a[4]==4){r4.setSelected(true);}
        else{buttonGroup1.clearSelection();}
        t1.setText(q[4]);
        r1.setText(a1[4]);
        r2.setText(b11[4]);
        r3.setText(c1[4]);
        r4.setText(d1[4]);
        if(a[i]==0){b5.setBackground(Color.red);}
        else{b5.setBackground(Color.cyan);}// TODO add your handling code here:
    }//GEN-LAST:event_b5ActionPerformed

    private void b2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b2ActionPerformed

        i=1;if(a[1]==1) {r1.setSelected(true);}
        else if(a[1]==2){r2.setSelected(true);}
        else if(a[1]==3){r3.setSelected(true);}
        else if(a[1]==4){r4.setSelected(true);}
        else{buttonGroup1.clearSelection();}
        t1.setText(q[1]);
        r1.setText(a1[1]);
        r2.setText(b11[1]);
        r3.setText(c1[1]);
        r4.setText(d1[1]);
        if(a[i]==0){b2.setBackground(Color.red);}
        else{b2.setBackground(Color.cyan);}// TODO add your handling code here:
    }//GEN-LAST:event_b2ActionPerformed

    private void r1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_r1ActionPerformed

    private void r3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_r3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(i<5){ if(r1.isSelected()){a[i]=1;}
            else if(r2.isSelected()){a[i]=2; }
            else if(r3.isSelected()){a[i]=3;}
            else if(r4.isSelected()){a[i]=4;}
            else{a[i]=0;}}

        if(i==4){JOptionPane.showMessageDialog(this,"move to next section!!!!!!");if(i==4){i++;if(a[4]==0){
            b5.setBackground(Color.red);  }
        else{b5.setBackground(Color.cyan);}i++;}}
        else if(i<5&&i>=0){i++;
            buttonGroup1.clearSelection();
            if(a[i]==1) {buttonGroup1.clearSelection();r1.setSelected(true);}
            else if(a[i]==2){buttonGroup1.clearSelection();r2.setSelected(true);}
            else if(a[i]==3){buttonGroup1.clearSelection();r3.setSelected(true);}
            else if(a[i]==4){buttonGroup1.clearSelection();r4.setSelected(true);}
            else{buttonGroup1.clearSelection();}
            t1.setText(q[i]);
            r1.setText(a1[i]);
            r2.setText(b11[i]);
            r3.setText(c1[i]);
            r4.setText(d1[i]);
            if(i==1)
            {
                // if(buttonGroup1.getSelection()==null)
                if(a[0]==0){
                    b1.setBackground(Color.red);  }
                else{b1.setBackground(Color.cyan);}
                b2.setBackground(Color.red);

            }
            else if(i==2)
            {
                if(a[1]==0){
                    b2.setBackground(Color.red);  }
                else{b2.setBackground(Color.cyan);}
                b3.setBackground(Color.red);

            }
            else if(i==3){
                if(a[2]==0){
                    b3.setBackground(Color.red);  }
                else{b3.setBackground(Color.cyan);}b4.setBackground(Color.red);
            }
            else if(i==4){if(a[3]==0){
                b4.setBackground(Color.red);  }
            else{b4.setBackground(Color.cyan);}b5.setBackground(Color.red);
        }

        }else{JOptionPane.showMessageDialog(this,"move to next section!!!!!!");}
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int x=JOptionPane.showConfirmDialog(this,"Do you want to exit","Confirm",JOptionPane.YES_NO_OPTION);
        if(x==0)
        { System.exit(0);}        // TODO add your handling code here:

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        buttonGroup1.clearSelection();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jPanel2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPanel2FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel2FocusGained

    private void b6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b6ActionPerformed
        i=5;        // TODO add your handling code here:
        if(a[5]==1) {r5.setSelected(true);}
        else if(a[5]==2){r6.setSelected(true);}
        else if(a[5]==3){r7.setSelected(true);}
        else if(a[5]==4){r8.setSelected(true);}
        else{buttonGroup1.clearSelection();}
        t2.setText(q[5]);
        r5.setText(a1[5]);
        r6.setText(b11[5]);
        r7.setText(c1[5]);
        r8.setText(d1[5]);
        if(a[i]==0){b6.setBackground(Color.red);}
        else{b6.setBackground(Color.cyan);}// TODO add your handling code here:
    }//GEN-LAST:event_b6ActionPerformed

    private void b8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b8ActionPerformed
        i=7;if(a[7]==1) {r5.setSelected(true);}
        else if(a[7]==2){r6.setSelected(true);}
        else if(a[7]==3){r7.setSelected(true);}
        else if(a[7]==4){r8.setSelected(true);}
        else{buttonGroup1.clearSelection();}
        t2.setText(q[7]);
        r5.setText(a1[7]);
        r6.setText(b11[7]);
        r7.setText(c1[7]);
        r8.setText(d1[7]); if(a[i]==0){b8.setBackground(Color.red);}
        else{b8.setBackground(Color.cyan);}       // TODO add your handling code here:
    }//GEN-LAST:event_b8ActionPerformed

    private void b9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b9ActionPerformed
        i=8;if(a[8]==1) {r5.setSelected(true);}
        else if(a[8]==2){r6.setSelected(true);}
        else if(a[8]==3){r7.setSelected(true);}
        else if(a[8]==4){r8.setSelected(true);}
        else{buttonGroup1.clearSelection();}
        t2.setText(q[8]);
        r5.setText(a1[8]);
        r6.setText(b11[8]);
        r7.setText(c1[8]);
        r8.setText(d1[8]);  if(a[i]==0){b9.setBackground(Color.red);}
        else{b9.setBackground(Color.cyan);}       // TODO add your handling code here:
    }//GEN-LAST:event_b9ActionPerformed

    private void b10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b10ActionPerformed
        i=9;if(a[9]==1) {r5.setSelected(true);}
        else if(a[9]==2){r6.setSelected(true);}
        else if(a[9]==3){r7.setSelected(true);}
        else if(a[9]==4){r8.setSelected(true);}
        else{buttonGroup1.clearSelection();}
        t2.setText(q[9]);
        r5.setText(a1[9]);
        r6.setText(b11[9]);
        r7.setText(c1[9]);
        r8.setText(d1[9]);  if(a[i]==0){b10.setBackground(Color.red);}
        else{b10.setBackground(Color.cyan);}         // TODO add your handling code here:
    }//GEN-LAST:event_b10ActionPerformed

    private void b7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b7ActionPerformed
        i=6;if(a[6]==1) {r5.setSelected(true);}
        else if(a[6]==2){r6.setSelected(true);}
        else if(a[6]==3){r7.setSelected(true);}
        else if(a[6]==4){r8.setSelected(true);}
        else{buttonGroup1.clearSelection();}
        t2.setText(q[6]);
        r5.setText(a1[6]);
        r6.setText(b11[6]);
        r7.setText(c1[6]);
        r8.setText(d1[6]);
        if(a[i]==0){b7.setBackground(Color.red);}
        else{b7.setBackground(Color.cyan);}// TODO add your handling code here:
    }//GEN-LAST:event_b7ActionPerformed

    private void r5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_r5ActionPerformed

    private void r7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_r7ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        if(i<10){ if(r5.isSelected()){a[i]=1;}
            else if(r6.isSelected()){a[i]=2; }
            else if(r7.isSelected()){a[i]=3;}
            else if(r8.isSelected()){a[i]=4;}
            else{a[i]=0;}}

        if(i==9){JOptionPane.showMessageDialog(this,"move to next section!!!!!!");i++;
            if(a[9]==0){
                b10.setBackground(Color.red);}

            else{b10.setBackground(Color.cyan);}}
        else if(i<10&&i>4){i++;buttonGroup1.clearSelection();
            if(a[i]==1) {buttonGroup1.clearSelection();r5.setSelected(true);}
            else if(a[i]==2){buttonGroup1.clearSelection();r6.setSelected(true);}
            else if(a[i]==3){buttonGroup1.clearSelection();r7.setSelected(true);}
            else if(a[i]==4){buttonGroup1.clearSelection();r8.setSelected(true);}
            else{buttonGroup1.clearSelection();}
            t2.setText(q[i]);
            r5.setText(a1[i]);
            r6.setText(b11[i]);
            r7.setText(c1[i]);
            r8.setText(d1[i]);

            if(i==6)
            {if(a[i-1]==0)
                {
                    b6.setBackground(Color.red);
                }
                else{b6.setBackground(Color.cyan);}
            }
            else if(i==7){
                if(a[i-1]==0)
                {
                    b7.setBackground(Color.red);
                }
                else{b7.setBackground(Color.cyan);}}
            else if(i==8){if(a[i-1]==0)
                {
                    b8.setBackground(Color.red);
                }
                else{b8.setBackground(Color.cyan);}}
            else if(i==9){if(a[i-1]==0)
                {
                    b9.setBackground(Color.red);
                }
                else{b9.setBackground(Color.cyan);}}
        }   else{JOptionPane.showMessageDialog(this,"move to next section!!!!!!");}     // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        int x=JOptionPane.showConfirmDialog(this,"Do you want to exit","Confirm",JOptionPane.YES_NO_OPTION);
        if(x==0)
        { System.exit(0);}          // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        buttonGroup1.clearSelection();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jPanel7FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPanel7FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel7FocusGained

    private void b12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b12ActionPerformed
        i=10;        // TODO add your handling code here:
        if(a[i]==1) {r9.setSelected(true);}
        else if(a[i]==2){r10.setSelected(true);}
        else if(a[i]==3){r11.setSelected(true);}
        else if(a[i]==4){r12.setSelected(true);}
        else{buttonGroup1.clearSelection();}
        t3.setText(q[i]);
        r9.setText(a1[i]);
        r10.setText(b11[i]);
        r11.setText(c1[i]);
        r12.setText(d1[i]);    if(a[i]==0){b12.setBackground(Color.red);}
        else{b12.setBackground(Color.cyan);}        // TODO add your handling code here:
    }//GEN-LAST:event_b12ActionPerformed

    private void b13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b13ActionPerformed
        i=12;
        if(a[i]==1) {r9.setSelected(true);}
        else if(a[i]==2){r10.setSelected(true);}
        else if(a[i]==3){r11.setSelected(true);}
        else if(a[i]==4){r12.setSelected(true);}
        else{buttonGroup1.clearSelection();}
        t3.setText(q[i]);
        r9.setText(a1[i]);
        r10.setText(b11[i]);
        r11.setText(c1[i]);
        r12.setText(d1[i]);
        if(a[i]==0){b13.setBackground(Color.red);}
        else{b13.setBackground(Color.cyan);}
    }//GEN-LAST:event_b13ActionPerformed

    private void b14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b14ActionPerformed
        i=13;        // TODO add your handling code here:
        // TODO add your handling code here:
        if(a[i]==1) {r9.setSelected(true);}
        else if(a[i]==2){r10.setSelected(true);}
        else if(a[i]==3){r11.setSelected(true);}
        else if(a[i]==4){r12.setSelected(true);}
        else{buttonGroup1.clearSelection();}
        t3.setText(q[i]);
        r9.setText(a1[i]);
        r10.setText(b11[i]);
        r11.setText(c1[i]);
        r12.setText(d1[i]);
        if(a[i]==0){b14.setBackground(Color.red);}
        else{b14.setBackground(Color.cyan);}// TODO add your handling code here:
    }//GEN-LAST:event_b14ActionPerformed

    private void b15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b15ActionPerformed
        i=14;        // TODO add your handling code here:
        // TODO add your handling code here:
        if(a[i]==1) {r9.setSelected(true);}
        else if(a[i]==2){r10.setSelected(true);}
        else if(a[i]==3){r11.setSelected(true);}
        else if(a[i]==4){r12.setSelected(true);}
        else{buttonGroup1.clearSelection();}
        t3.setText(q[i]);
        r9.setText(a1[i]);
        r10.setText(b11[i]);
        r11.setText(c1[i]);
        r12.setText(d1[i]);
        if(a[i]==0){b15.setBackground(Color.red);}
        else{b15.setBackground(Color.cyan);}        // TODO add your handling code here:
    }//GEN-LAST:event_b15ActionPerformed

    private void b16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b16ActionPerformed
        i=11;        // TODO add your handling code here:
        if(a[i]==1) {r9.setSelected(true);}
        else if(a[i]==2){r10.setSelected(true);}
        else if(a[i]==3){r11.setSelected(true);}
        else if(a[i]==4){r12.setSelected(true);}
        else{buttonGroup1.clearSelection();}
        t3.setText(q[i]);
        r9.setText(a1[i]);
        r10.setText(b11[i]);
        r11.setText(c1[i]);
        r12.setText(d1[i]);
        if(a[i]==0){b16.setBackground(Color.red);}
        else{b16.setBackground(Color.cyan);}        // TODO add your handling code here:
    }//GEN-LAST:event_b16ActionPerformed

    private void r9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_r9ActionPerformed

    private void r11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_r11ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        if(i<15){ if(r9.isSelected()){a[i]=1;}
            else if(r10.isSelected()){a[i]=2; }
            else if(r11.isSelected()){a[i]=3;}
            else if(r12.isSelected()){a[i]=4;}
            else{a[i]=0;}}

        if(i==14){JOptionPane.showMessageDialog(this,"move to next section!!!!!!");
            if(i==14){
                i++;
                if(a[14]==0)
                {
                    b15.setBackground(Color.red);
                }
                else{b15.setBackground(Color.cyan);}}}
        else if(i<14&&i>8){i++; buttonGroup1.clearSelection();
            if(a[i]==1) {buttonGroup1.clearSelection();r9.setSelected(true);}
            else if(a[i]==2){buttonGroup1.clearSelection();r10.setSelected(true);}
            else if(a[i]==3){buttonGroup1.clearSelection();r11.setSelected(true);}
            else if(a[i]==4){buttonGroup1.clearSelection();r12.setSelected(true);}
            else{buttonGroup1.clearSelection();}
            t3.setText(q[i]);
            r9.setText(a1[i]);
            r10.setText(b11[i]);
            r11.setText(c1[i]);
            r12.setText(d1[i]);
            if(i==11){if(a[i-1]==0)
                {
                    b12.setBackground(Color.red);
                }
                else{b12.setBackground(Color.cyan);}}
            if(i==12){
                if(a[i-1]==0)
                {
                    b16.setBackground(Color.red);
                }
                else{b16.setBackground(Color.cyan);}}
            if(i==13){if(a[i-1]==0)
                {
                    b13.setBackground(Color.red);
                }
                else{b13.setBackground(Color.cyan);}}
            if(i==14){if(a[i-1]==0)
                {
                    b14.setBackground(Color.red);
                }
                else{b14.setBackground(Color.cyan);}}
        }   else if(i>14){JOptionPane.showMessageDialog(this,"move to next section!!!!!!");}           // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        int x=JOptionPane.showConfirmDialog(this,"Do you want to exit","Confirm",JOptionPane.YES_NO_OPTION);
        if(x==0)
        { System.exit(0);}         // TODO add your handling code here:
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        buttonGroup1.clearSelection();         // TODO add your handling code here:
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jPanel9FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPanel9FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel9FocusGained

    private void b17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b17ActionPerformed
        i=15;        // TODO add your handling code here:
        if(a[i]==1) {r13.setSelected(true);}
        else if(a[i]==2){r14.setSelected(true);}
        else if(a[i]==3){r15.setSelected(true);}
        else if(a[i]==4){r16.setSelected(true);}
        else{buttonGroup1.clearSelection();}
        t4.setText(q[i]);
        r13.setText(a1[i]);
        r14.setText(b11[i]);
        r15.setText(c1[i]);
        r16.setText(d1[i]);
        if(a[i]==0){b17.setBackground(Color.red);}
        else{b17.setBackground(Color.cyan);}// TODO add your handling code here:
    }//GEN-LAST:event_b17ActionPerformed

    private void b21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b21ActionPerformed
        i=16;        // TODO add your handling code here:
        if(a[i]==1) {r13.setSelected(true);}
        else if(a[i]==2){r14.setSelected(true);}
        else if(a[i]==3){r15.setSelected(true);}
        else if(a[i]==4){r16.setSelected(true);}
        else{buttonGroup1.clearSelection();}
        t4.setText(q[i]);
        r13.setText(a1[i]);
        r14.setText(b11[i]);
        r15.setText(c1[i]);
        r16.setText(d1[i]);
        if(a[i]==0){b21.setBackground(Color.red);}
        else{b21.setBackground(Color.cyan);}// TODO add your handling code here:
    }//GEN-LAST:event_b21ActionPerformed

    private void r13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_r13ActionPerformed

    private void r14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_r14ActionPerformed

    private void r15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_r15ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        if(i<17){ if(r13.isSelected()){a[i]=1;}
            else if(r14.isSelected()){a[i]=2; }
            else if(r15.isSelected()){a[i]=3;}
            else if(r16.isSelected()){a[i]=4;}
            else{a[i]=0;}}
        buttonGroup1.clearSelection();
        if(i==16){JOptionPane.showMessageDialog(this,"you have reached the end of test!!!!!!");
            if(a[16]==0){b21.setBackground(Color.red);}
            else{b21.setBackground(Color.cyan);}

        }
        else{i++;
            if(a[i]==1) {buttonGroup1.clearSelection();r13.setSelected(true);}
            else if(a[i]==2){buttonGroup1.clearSelection();r14.setSelected(true);}
            else if(a[i]==3){buttonGroup1.clearSelection();r15.setSelected(true);}
            else if(a[i]==4){buttonGroup1.clearSelection();r16.setSelected(true);}
            else{buttonGroup1.clearSelection();}
            t4.setText(q[i]);
            r13.setText(a1[i]);
            r14.setText(b11[i]);
            r15.setText(c1[i]);
            r16.setText(d1[i]);
            if(i==16){if(a[i-1]==0){b17.setBackground(Color.red);}
                else{b17.setBackground(Color.cyan);}}
        }         // TODO add your handling code here:
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        int x=JOptionPane.showConfirmDialog(this,"Do you want to exit","Confirm",JOptionPane.YES_NO_OPTION);
        if(x==0)
        { System.exit(0);}         // TODO add your handling code here:
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        buttonGroup1.clearSelection();         // TODO add your handling code here:
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jPanel11FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPanel11FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel11FocusGained

    private void tbStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_tbStateChanged
        // TODO add your handling code here:
        //JOptionPane.showMessageDialog(this,(tb.getSelectedIndex()));
        int x=tb.getSelectedIndex();
        if(x==0)
        {i=0;}
        else if(x==1){i=5;t1.setText(q[i]);
            r1.setText(a1[i]);
            r2.setText(b11[i]);
            r3.setText(c1[i]);
            r4.setText(d1[i]);}
        else if(x==2)
        {i=10;t1.setText(q[i]);t1.setText(q[i]);
            r1.setText(a1[i]);
            r2.setText(b11[i]);
            r3.setText(c1[i]);
            r4.setText(d1[i]);;
            r1.setText(a1[i]);
            r2.setText(b11[i]);
            r3.setText(c1[i]);
            r4.setText(d1[i]);}
        else{i=15;t1.setText(q[i]);
            r1.setText(a1[i]);
            r2.setText(b11[i]);
            r3.setText(c1[i]);
            r4.setText(d1[i]);}
        if(a[i]==1) {buttonGroup1.clearSelection();r13.setSelected(true);}
        else if(a[i]==2){buttonGroup1.clearSelection();r14.setSelected(true);}
        else if(a[i]==3){buttonGroup1.clearSelection();r15.setSelected(true);}
        else if(a[i]==4){buttonGroup1.clearSelection();r16.setSelected(true);}
        else{buttonGroup1.clearSelection();}
    }//GEN-LAST:event_tbStateChanged

    private void tbFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tbFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_tbFocusGained

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);b12.setBackground(Color.red);b17.setBackground(Color.red);b1.setBackground(Color.red);        // TODO add your handling code here:
        b6.setBackground(Color.red);
     for(i=0;i<17;i++){a[i]=0;a1[i]="";b11[i]="";c1[i]="";d1[i]="";}
     i=17;    
         
         try{abc(); 
String query="select * from questions;";
        //    stmt.executeQuery(query);
           ResultSet rs=stmt.executeQuery(query);
       
           for(int b=0;b<17;b++)
           {
           rs.next(); 
           q[b]=rs.getString("q");
           a1[b]=rs.getString("a");
           b11[b]=rs.getString("b");
           c1[b]=rs.getString("c");
           d1[b]=rs.getString("d");
           }
         t1.setText(q[0]);
         r1.setText(a1[0]);
         r2.setText(b11[0]);
         r3.setText(c1[0]);
         r4.setText(d1[0]);
       i=0;
        t2.setText(q[5]);
         r5.setText(a1[5]);
         r6.setText(b11[5]);
         r7.setText(c1[5]);
         r8.setText(d1[5]);
         
         t3.setText(q[10]);
            r9.setText(a1[10]);
            r10.setText(b11[10]);
            r11.setText(c1[10]);
            r12.setText(d1[10]);
            t4.setText(q[15]);
            r13.setText(a1[15]);
            r14.setText(b11[15]);
            r15.setText(c1[15]);
            r16.setText(d1[15]);
}
 catch(Exception  f){JOptionPane.showMessageDialog(this,f.getMessage());  } // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mock_test.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mock_test.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mock_test.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mock_test.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mock_test().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b1;
    private javax.swing.JButton b10;
    private javax.swing.JButton b12;
    private javax.swing.JButton b13;
    private javax.swing.JButton b14;
    private javax.swing.JButton b15;
    private javax.swing.JButton b16;
    private javax.swing.JButton b17;
    private javax.swing.JButton b2;
    private javax.swing.JButton b21;
    private javax.swing.JButton b3;
    private javax.swing.JButton b4;
    private javax.swing.JButton b5;
    private javax.swing.JButton b6;
    private javax.swing.JButton b7;
    private javax.swing.JButton b8;
    private javax.swing.JButton b9;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JRadioButton r1;
    private javax.swing.JRadioButton r10;
    private javax.swing.JRadioButton r11;
    private javax.swing.JRadioButton r12;
    private javax.swing.JRadioButton r13;
    private javax.swing.JRadioButton r14;
    private javax.swing.JRadioButton r15;
    private javax.swing.JRadioButton r16;
    private javax.swing.JRadioButton r2;
    private javax.swing.JRadioButton r3;
    private javax.swing.JRadioButton r4;
    private javax.swing.JRadioButton r5;
    private javax.swing.JRadioButton r6;
    private javax.swing.JRadioButton r7;
    private javax.swing.JRadioButton r8;
    private javax.swing.JRadioButton r9;
    private javax.swing.JTextArea t1;
    private javax.swing.JTextArea t2;
    private javax.swing.JTextArea t3;
    private javax.swing.JTextArea t4;
    private javax.swing.JTabbedPane tb;
    // End of variables declaration//GEN-END:variables
}
