
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Student
 */
public class sign_up extends javax.swing.JFrame {

    /**
     * Creates new form sign_up
     */
    public sign_up() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        t1 = new javax.swing.JTextField();
        c1 = new javax.swing.JComboBox<>();
        c2 = new javax.swing.JComboBox<>();
        c3 = new javax.swing.JComboBox<>();
        r1 = new javax.swing.JRadioButton();
        r2 = new javax.swing.JRadioButton();
        t2 = new javax.swing.JTextField();
        t3 = new javax.swing.JTextField();
        t4 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        t5 = new javax.swing.JPasswordField();
        t6 = new javax.swing.JPasswordField();
        jButton2 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Book Antiqua", 3, 18)); // NOI18N
        jLabel1.setText("Name");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 60, -1));

        jLabel2.setFont(new java.awt.Font("Book Antiqua", 3, 18)); // NOI18N
        jLabel2.setText("Date of Birth");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 110, 30));

        jLabel3.setFont(new java.awt.Font("Book Antiqua", 3, 18)); // NOI18N
        jLabel3.setText("Gender");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 70, -1));

        jLabel5.setFont(new java.awt.Font("Book Antiqua", 3, 18)); // NOI18N
        jLabel5.setText("Mobile No.");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 100, 20));

        jLabel6.setFont(new java.awt.Font("Book Antiqua", 3, 18)); // NOI18N
        jLabel6.setText("Email-ID");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 90, 30));

        jLabel7.setFont(new java.awt.Font("Book Antiqua", 3, 18)); // NOI18N
        jLabel7.setText("Confirm Email-ID");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, -1, -1));

        t1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                t1FocusGained(evt);
            }
        });
        t1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                t1KeyTyped(evt);
            }
        });
        getContentPane().add(t1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 80, 310, 30));

        c1.setFont(new java.awt.Font("Georgia", 3, 18)); // NOI18N
        c1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        c1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c1ActionPerformed(evt);
            }
        });
        getContentPane().add(c1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 120, 60, 40));

        c2.setFont(new java.awt.Font("Georgia", 3, 14)); // NOI18N
        c2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "January", "Feburary", "March", "April", "May ", "June", "July", "August", "September", "October", "November", "December" }));
        getContentPane().add(c2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 120, -1, 40));

        c3.setFont(new java.awt.Font("Georgia", 3, 14)); // NOI18N
        c3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1992", "1993", "1994", "1995", "1996", "1997", "1998", "1999", "2000", "2001" }));
        getContentPane().add(c3, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 120, 90, 40));

        r1.setFont(new java.awt.Font("Georgia", 3, 14)); // NOI18N
        r1.setText("Male");
        getContentPane().add(r1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 180, 80, -1));

        r2.setFont(new java.awt.Font("Georgia", 3, 14)); // NOI18N
        r2.setText("Female");
        getContentPane().add(r2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 180, 110, -1));

        t2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                t2FocusLost(evt);
            }
        });
        t2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                t2KeyTyped(evt);
            }
        });
        getContentPane().add(t2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 230, 190, 30));

        t3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t3ActionPerformed(evt);
            }
        });
        getContentPane().add(t3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 280, 370, 30));

        t4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t4ActionPerformed(evt);
            }
        });
        getContentPane().add(t4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 340, 370, 30));

        jButton1.setFont(new java.awt.Font("Algerian", 3, 36)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 153));
        jButton1.setText("SIGNUP");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 190, 230, 70));

        jLabel4.setFont(new java.awt.Font("Book Antiqua", 3, 48)); // NOI18N
        jLabel4.setText("Sign Up for PST");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 0, -1, -1));

        jLabel11.setFont(new java.awt.Font("Book Antiqua", 3, 18)); // NOI18N
        jLabel11.setText("Confirm Password");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 460, 160, 30));

        jLabel10.setFont(new java.awt.Font("Book Antiqua", 3, 18)); // NOI18N
        jLabel10.setText("Password");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, 140, 30));

        t5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t5ActionPerformed(evt);
            }
        });
        getContentPane().add(t5, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 410, 370, 30));
        getContentPane().add(t6, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 460, 370, 30));

        jButton2.setFont(new java.awt.Font("Georgia", 3, 10)); // NOI18N
        jButton2.setText("Back To Homepage");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 470, 140, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AIEEE-Examination-Form.jpg"))); // NOI18N
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 730, 510));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void t1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_t1FocusGained
        //JOptionPane.showMessageDialog(this,"PLEASE ENTER YOUR NAME IN CAPITAL LETTERS!!");
        // TODO add your handling code here:
    }//GEN-LAST:event_t1FocusGained

    private void c1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c1ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_c1ActionPerformed

    private void t2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_t2FocusLost
        // TODO add your handling code here:
        String mob=t2.getText();char ch=' ';int b=0;
        if(mob.length()==10){
            for(int i=0;i<10;i++)
            {ch=mob.charAt(i);
                if(ch>=48&&ch<=57)
                {;}
                else{b++;break;}
            }
        }
        else{b++;}
        if(b!=0)
        {
            JOptionPane.showMessageDialog(this,"enter correct mobile no");
            t2.setText("");
            b=0;
            t2.requestFocus();
        }
    }//GEN-LAST:event_t2FocusLost

    private void t2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t2KeyTyped
        // TODO add your handling code here:
        char key = evt.getKeyChar();
        if (!(key>='0' && key<='9'))
        evt.consume();
    }//GEN-LAST:event_t2KeyTyped

    private void t3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t3ActionPerformed

    private void t4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String name=t1.getText();
        String date=(String) c1.getSelectedItem();
        String month=(String)c2.getSelectedItem();
        String year=(String)c3.getSelectedItem();
        if(r1.isSelected())
        {
            String m=r1.getText();
        }
        else if(r2.isSelected())
        {
            String f=r2.getText();
        }
        String mob=t2.getText();
        String email=t3.getText();
        String confirmemail=t4.getText();
        String pass=t5.getText();
        String confirmpass=t6.getText();
        String dob=date+"/"+month+"/"+year;

        if(name.isEmpty())
        JOptionPane.showMessageDialog(this, "Name not entered !!");
        else if(r1.isSelected()==false && r2.isSelected()==false)
        JOptionPane.showMessageDialog(this, "Please select your gender !!");
        else if(t2.getText().isEmpty())
        JOptionPane.showMessageDialog(this, "Mobile no. not entered !!");
        else if(email.isEmpty())
        JOptionPane.showMessageDialog(this, "email not entered !!");
        else if(confirmemail.isEmpty())
        JOptionPane.showMessageDialog(this, "Please enter your email again !!");
        else if(pass.isEmpty())
        JOptionPane.showMessageDialog(this, "Password not entered !!");
        else if(confirmpass.isEmpty())
        JOptionPane.showMessageDialog(this, "Please enter your password again !!");
        else if(email.equals(confirmemail)==false)
        JOptionPane.showMessageDialog(this, "Email do not match..!!");
        else if(pass.equals(confirmpass)==false)
        JOptionPane.showMessageDialog(this, "Passwords do not match..!!");
        // if((pass.equals(confirmpass)==true) && (pass.equals(confirmpass)==true))
        else {
            try
            {
                Class.forName("java.sql.DriverManager");
                Connection con= (Connection)
                DriverManager.getConnection("jdbc:mysql://localhost:3306/pst","root" ,"");
                Statement stmt = (Statement) con.createStatement();
                String gender="";
                if(r1.isSelected()==true)
                gender="male";
                else
                gender="female";
                String query="INSERT INTO signup VALUES ('"+name+"' , '"+dob+"','"+gender+"','"+email+"','"+pass+"','"+mob+"');";
                stmt.executeUpdate(query);
                t1.setText("");
                t2.setText("");
                t3.setText("");
                t4.setText("");
                t5.setText("");
                t6.setText("");
                r1.setSelected(false);
                r2.setSelected(false);
                 JOptionPane.showMessageDialog(this, "You have signed up succesfully !!");
                 new home_page().setVisible(true); this.dispose();
            }
            catch (Exception e)
            {
                JOptionPane.showMessageDialog(this, e.getMessage());
            }
        }
        // JOptionPane.showMessageDialog(this, "You have signed up succesfully !!");

    }//GEN-LAST:event_jButton1ActionPerformed

    private void t5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t5ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        new home_page().setVisible(true);this.dispose();           // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void t1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t1KeyTyped
        // TODO add your handling code here:
        char key = evt.getKeyChar();
        if((key>='a' && key<='z')){ JOptionPane.showMessageDialog(this, "Please enter your name in capital letters");}
        if ((key>='A'&&key<='Z')||key==32)
        {}else{
            evt.consume();}
    }//GEN-LAST:event_t1KeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(sign_up.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(sign_up.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(sign_up.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(sign_up.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new sign_up().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> c1;
    private javax.swing.JComboBox<String> c2;
    private javax.swing.JComboBox<String> c3;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton r1;
    private javax.swing.JRadioButton r2;
    private javax.swing.JTextField t1;
    private javax.swing.JTextField t2;
    private javax.swing.JTextField t3;
    private javax.swing.JTextField t4;
    private javax.swing.JPasswordField t5;
    private javax.swing.JPasswordField t6;
    // End of variables declaration//GEN-END:variables
}
